### ISSUE TITLE
 Review https://github.com/LiberTEM/LiberTEM/security/dependabot and update dependencies

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1046]
Deferred from 0.7 release, but still TODO to avoid bitrot.

**Comment by sk1p** [comment]
Related to this: https://github.com/facebook/create-react-app/issues/11174 - we need to make sure we keep all build-time dependencies that don't end up in the resulting js bundle in the `devDependencies`, otherwise we will keep getting irrelevant security warnings. I think GitHub also fixed something related to this, as there are no dependabot alerts remaining right now.
