### ISSUE TITLE
Improve OpenBLAS dgemm for low number of masks

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#21]
In #14 we found some cases where matrix-matrix multiplication was not as efficient as it could be for some input sizes. We should improve OpenBLAS for these cases.

**Comment by uellue** [comment]
I'm closing this because PyTorch seems to be solving this issue for us. Without having looked at the details, the 2x performance gain of PyTorch would be pretty much what optimizing OpenBLAS would yield. I bet 1 € that PyTorch does an equivalent of the blocking strategy we found in #14 because that's where there's an obvious potential for such an improvement over OpenBLAS. :-)
