### ISSUE TITLE
Highlight the focus for keyboard controls

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#211]
This relates to the keyboard controls in #164 

Right now it can be difficult to tell which element has the focus for keyboard controls.

Perhaps change the pointer or somehow highlight the display that has keyboard focus, just like the text boxes here at GitHub?

**Comment by sk1p** [comment]
Agreed - having some kind of outline for focused elements is a best practice. Need to check how to implement this for SVG elements. The default outline is sadly quite ugly...

Quick mockup:

![selection_068](https://user-images.githubusercontent.com/5778/50598044-cb9f7e00-0ea9-11e9-98d3-c41dfa0512ae.png)

**Comment by uellue** [comment]
Looks good to me!

Here's how Inkscape does it:
![image](https://user-images.githubusercontent.com/25689052/50734226-62b35100-119c-11e9-8d04-e79a1c81be94.png)

Would it make sense to follow the style of Inkscape, just to have a familiar look?

**Comment by sk1p** [comment]
I implemented a first version of this in the complex branch, which will be merged soon. I just change the color when the handle has keyboard focus. I kind of dislike the Inkscape way a bit, because filling the circles will hide what's behind them. Maybe we should wait for some user feedback before making further changes.

**Comment by uellue** [comment]
Looks good! :-)
