### ISSUE TITLE
Cleanup DataSet implementations

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#252]
- [x] abstract out some helper functions or methods in the base DataSet or helper classes.
- [x] all `Partition`s and `DataTile`s should have flat navigation (signal can still be ND).
- [x] `get_tiles` needs to support some more parameters (`mmap`, `full_frames`, `dest_dtype`). 
- [x] tests for the new EMPAD reader
- [x] better partition sizing (needs total number of cores from executor!)
- [x] finish I/O capability system
  - [x] make capabilities available to `DataSet`, not only `FileSet3D` impls (maybe put them into `DataSetMeta` and make it a required part of `FileSet3D`?)
  - [x] capabilities can be dynamic (for example, they can depend on parameters or format details like pixel types (MIB 1bit can't be mapped as bool ndarray, other types can!))

Status: all `DataSet` impls should be on feature-parity now, tests pass.

**Comment by sk1p** [comment]
Part of this is now available in the `ds-refactor` branch

**Comment by uellue** [comment]
Currently, a small DataSet may consist of only one partition if the partitioning is calculated automatically. 

As a consequence, CPU-intensive calculations will only use one core.

In the future, a DataSet should have at least as many partitions as cores are available in the cluster so that CPU-intensive processing uses all available resources.
