### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#443]
We should add a step "write release notes" to the release process, and think about if/how we want to automate putting it into the [GitHub release](https://github.com/LiberTEM/LiberTEM/releases) and other places (documentation?)

Possible tool to use: https://pypi.org/project/towncrier/

**Comment by uellue** [comment]
A few preliminary thoughts:

In my opinion it would be useful to have change information on the current master branch on the homepage as well, not only for full releases, since many people actually use the Git version.

Change information should be displayed everywhere where it is appropriate and relevant:

* Global change log with high-level content and link to further information, similar to current release message. These messages were well-received so far.
  * That should include depreciation warnings if users may have to change code at some point.
* Change information in docstrings: When introduced, when depreciated or changed. See also https://numpydoc.readthedocs.io/en/latest/format.html#sections "Depreciation warning"
* Change log at the top of each example
* In the appropriate context in documentation, like *This feature was introduced in version 0.2.* as a note or similar

Many software packages maintain documentation for each version online. I am not sure if that makes too much sense, with the exception of really long-lived branches like python2 vs python3. Instead, I found context information in the most recent documentation (like: *This describes the behavior in version 1.2 and newer. Previously, it worked like this and that.*) more helpful. Older versions can lead to confusion since Google still finds them and they inherently don't contain forward-looking context -- I'd never know that the described function is depreciated in a newer release!

I've looked at `towncrier` from all sides and developed the thoughts that I described above. In my opinion, it would perhaps be simpler to just maintain a change log as a file. Our development is pretty linear and we can perhaps manage merge conflicts manually when they actually occur. The biggest obstacle IMO is that `towncrier` can't merge new items into existing entries, which makes it difficult to maintain a pretty change log for the development branch.

A point to consider would be that we only really know the version of a feature when we are making the release. Perhaps we can just use the current dev release, like `0.3.0.dev0` during development and alter all occurrences when we are making the release, for example as part of baking an RC?
