### ISSUE TITLE
Error while loading Raw dataset on windows

### ISSUE THREAD

**Issue by AyushGit123** [LiberTEM/LiberTEM#693]
While loading a raw dataset produced using python script given on [website](https://libertem.github.io/LiberTEM/sample_datasets.html) , an error is displayed which says module " 'os' has no attribute 'O_DIRECT' " I do not know why this error is displayed . 
![Screenshot (1)](https://user-images.githubusercontent.com/44500830/77660213-0c981c80-6f9f-11ea-8323-15083b074e73.png)

**Comment by sk1p** [comment]
Which version of LiberTEM are you using? Windows does not support direct I/O, so if you are enabling it, you will get either this message with LiberTEM v0.4.1 or older, or a more friendly message with the current git version (since https://github.com/LiberTEM/LiberTEM/pull/659 by @AnandBaburajan was merged)

**Comment by sk1p** [comment]
As discussed in the gitter chat, this was still LiberTEM v0.4.1, so this error is expected and replaced by a better message in #658
