### ISSUE TITLE
Live view widgets for LiberTEM results in Jupyter notebooks etc

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#980]
Right now, live updating results in a Jupyter notebook have to be coded by hand using the internal asynchronous API.

In the future, it would be nice to be able to automate that and get a live updating view of a running UDF with a few simple commands, for example for live data processing.

Possible libraries to use:

* https://github.com/bqplot/bqplot
* https://github.com/glue-viz/bqplot-image-gl

Thx @jacobjma for the pointers!

**Comment by sk1p** [comment]
In addition to these libraries, we can also still support something based on `matplotlib`, just with a slower update-rate. I tried `bqplot` - one of the downsides currently is the effort spent when installing. I somehow managed to mess up my environment, and also it seems that `bqplot` needs to be not only installed in the environment where the kernel is running, but also in the `jupyter` environment. This can be harder on some systems, for example `jupyterhub` installations on some servers, or even on HPC infrastructure like the JSC, where it probably won't be considered.

Maybe I was also missing something else - it's just that without installing `bqplot` into the `jupyter` environment, it threw JavaScript errors which I couldn't reliably track down to any specific root cause.
